config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root 'static_pages#index'

  resources :users, :only => [:index, :show]
  resources :posts, :only => [:create, :destroy]
  resources :relationship_requests, :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :content, presence: true
end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :friender, class_name: "User"
  belongs_to :friendee, class_name: "User"

  validates :friender_id, presence: true
  validates :friendee_id, presence: true

  def return_inverse_role(user)
    if user == friender
      friendee
    elsif user == friendee
      friender
    end
  end

end

app/models/relationship_request.rb
class RelationshipRequest < ApplicationRecord
  belongs_to :requester, class_name: "User"
  belongs_to :requestee, class_name: "User"

  validates :requester_id, presence: true
  validates :requestee_id, presence: true

  validates :requestee_id, uniqueness: { scope: :requester_id,
                                         message: ->(object, data) do
                                          "^#{object.requestee.first_name} has already been sent a friend request"
                                         end }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, :last_name, presence: true,
                                     format: { with: /\A[a-zA-Z]+\z/, message: "should only allow letters" }

  has_many :posts, dependent: :destroy

  has_many :friend_requests, { class_name: :RelationshipRequest, foreign_key: :requester_id, dependent: :destroy }
  has_many :relationship_requests, { class_name: :RelationshipRequest, foreign_key: :requester_id, dependent: :destroy }
  has_many :friend_requests_received, { class_name: :RelationshipRequest, foreign_key: :requestee_id, dependent: :destroy }
  has_many :relationship_requests_received, { class_name: :RelationshipRequest, foreign_key: :requestee_id, dependent: :destroy }
  has_many :pending_friends, { through: :friend_requests, source: :requestee }
  has_many :pending_friends_inverse, { through: :friend_requests_received, source: :requester }

  has_many :friendships, { class_name: :Relationship, foreign_key: :friender_id, dependent: :destroy }
  has_many :inverse_friendships, { class_name: :Relationship, foreign_key: :friendee_id, dependent: :destroy }
  has_many :friends_as_requester, { through: :friendships, source: :friendee }
  has_many :friends_as_requestee, { through: :inverse_friendships, source: :friender }

  before_save :capitalize_first_and_last_name
  before_save :downcase_email

  def feed 
    Post.where("user_id IN (?) OR user_id = ?", friends.pluck(:id), id)
  end

  def full_name
    first_name + " " + last_name
  end

  def friends
    friends_as_requestee + friends_as_requester
  end

  def specific_friendship_with(user)
    friendships.find_by(friendee: user) || inverse_friendships.find_by(friender: user)
  end

  private

    def capitalize_first_and_last_name
      first_name.capitalize!
      last_name.capitalize!
    end

    def downcase_email
      email.downcase!
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController


  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:notice] = "Post created!"
    else
      flash[:notice] = "Post can't be empty."
    end

    redirect_back fallback_location: current_user
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:success] = "Post deleted."
    redirect_back fallback_location: current_user
  end

  private

    def post_params
      params.require(:post).permit(:content)
    end
end

app/controllers/relationship_requests_controller.rb
class RelationshipRequestsController < ApplicationController

    def create
      requestee = User.find(params[:requestee_id])
      @friend_request = current_user.friend_requests.build(requestee: requestee)

      if @friend_request.save
        flash[:notice] = "Friend request has been sent to #{requestee.first_name}"
      else
        flash[:alert] = @friend_request.errors.full_messages.first_name
      end
      
      redirect_back fallback_location: current_user
    end

    def destroy
      @friend_request = RelationshipRequest.find(params[:id])
      @friend_request.destroy
      flash[:notice] = "Friend request cancelled."

      redirect_back fallback_location: current_user
    end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    friender = User.find(params[:friender_id])
    @relationship = friender.friendships.build(friendee: current_user)

    if @relationship.save
      flash[:notice] = "Accepted friend request."
      @relationship_request = RelationshipRequest.find_by(requestee_id: current_user.id, requester_id: params[:friender_id])
      @relationship_request.delete
    else
      flash[:alert] = @relationship.errors.full_messages.first
    end

    redirect_back fallback_location: current_user
  end

  def destroy
    @relationship = Relationship.find(params[:id])
    @relationship.destroy
    @unfriended_user = @relationship.return_inverse_role(current_user)
    flash[:notice] = "#{@unfriended_user.first_name} unfriended."

    redirect_back fallback_location: current_user
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
    if user_signed_in?
      redirect_to current_user
    else
      redirect_to new_user_session_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @post = @user.posts.build
    @feed_items = @user.feed.paginate(page: params[:page])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationship_requests_helper.rb
module RelationshipRequestsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header>
  <nav class="round">
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <% if user_signed_in? %>
        <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
      <% else %>
        <li><%= link_to "Sign in", new_user_session_path %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinSocialNetwork</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="alerts">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
    </div>
    <%= yield %>

    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/posts/_post.html.erb
<li id="post-<%= post.id %>">
  <span class="user"><%= link_to post.user.first_name, post.user %></span>
  <span class="content"><%= post.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(post.created_at) %> ago.
    <% if current_user == post.user %>
      <%= link_to "delete", post, method: :delete,
                                       data: { confirm: "You sure?" } %>
    <% end %>
  </span>
</li>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="posts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@post) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new post..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_relationship_buttons.html.erb
<% if user_signed_in? &&
      user != nil &&
      current_user != user &&
      !current_user.pending_friends.include?(user) &&
      !current_user.pending_friends_inverse.include?(user) &&
      !current_user.friends.include?(user) %>

  <%= button_to("Add friend", relationship_requests_path, params: {requestee_id: user.id } ) %>
<% end %>

<% if user_signed_in? && current_user.pending_friends.include?(user) %>
  <%= button_to("Cancel Friend Request",
                relationship_request_path(current_user.relationship_requests.find_by(requestee: user)),
                method: :delete)  %>
<% end %>

<% if user_signed_in? &&
         (current_user.friends_as_requester.include?(user) ||
         current_user.friends_as_requestee.include?(user)) %>
  <%= button_to("Unfriend",
                relationship_path(current_user.specific_friendship_with(user)),
                method: :delete) %>
<% end %>

<% if user_signed_in? &&
   current_user.pending_friends_inverse.include?(user) %>
   <% byebug %>
   <%= button_to("Accept Friend Request", relationships_path, params: { friender_id: user.id }) %>
<% end %>

app/views/static_pages/index.html.erb
Home

app/views/users/index.html.erb
<h1>All Users</h1>
<table>
  <% @users.each do |user| %>
    <tr>
      <td>
        <%= link_to user.first_name, user %>
        <%= render 'shared/relationship_buttons', user: user %>
      </td>
    </tr>
  <% end %>
</table>

app/views/users/show.html.erb
<h1><%= @user.first_name %></h1>
<%= render 'shared/relationship_buttons', user: @user %>

<% if @user == current_user %>
  <h2>Make a post</h2>
  <%= render 'shared/micropost_form' %>
<% end %>

<h2>Feed</h2>
<%= render 'shared/feed' %>